line:
  CHANNEL_SECRET: 51de3773036ea50afdba0836f6454018
  CHANNEL_TOKEN: 8AgOT7UHy3ypdFinyOdtM5/fR1rv85e+LRrKf0fsauW+SN6m5YmJ2tL5l9HEPAyrHStpGd7S2zoYYA16EdOm2n/rgf0HPYqz8R0xxSwIWqQkRbrq7buWdlalJLxzxlQQmiXABHjQYMm+tl0jJypb1AdB04t89/1O/w1cDnyilFU=

db:
  server: localhost
  driver: SQLEXPRESS
  database: QueueSystem
